# Generated by Django 5.2.7 on 2025-11-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gameprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='best_times',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='level_stars',
            field=models.JSONField(default=dict),
        ),
    ]
