# Generated by Django 5.2.7 on 2025-11-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendrequest_friendship'),
        ('accounts', '0005_gameprogress_best_times_gameprogress_deaths_and_more'),
    ]

    operations = [
    ]
