# Generated by Django 5.2.7 on 2025-11-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_gameprogress_best_times_gameprogress_deaths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_index', models.IntegerField(unique=True)),
                ('district', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
