# Generated by Django 5.2.7 on 2025-11-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_foodcard'),
        ('accounts', '0006_merge_20251124_2316'),
    ]

    operations = [
    ]
