# Generated by Django 5.2.7 on 2025-11-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0006_foodcard_0006_merge_20251124_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcard',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodcard',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
