# Generated by Django 5.2.7 on 2025-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0006_foodcard_0006_merge_20251124_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
