# Generated by Django 5.2.7 on 2025-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_foodcard_image_url_foodcard_price_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='collected_ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gameprogress',
            name='unlocked_recipes',
            field=models.JSONField(default=list),
        ),
    ]
