# Generated by Django 5.2.7 on 2025-11-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gameprogress_collected_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCard',
        ),
        migrations.DeleteModel(
            name='GameProgress',
        ),
    ]
