# Generated by Django 5.2.7 on 2025-11-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_current_streak_and_more'),
        ('accounts', '0011_puzzleprogress'),
    ]

    operations = [
    ]
