# Generated by Django 5.2.7 on 2025-12-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_foodplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFoodPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Chỉ xem'), ('edit', 'Xem và chỉnh sửa')], default='edit', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('food_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accounts.foodplan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_plans_as_owner', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shared_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'unique_together': {('food_plan', 'shared_with')},
            },
        ),
        migrations.CreateModel(
            name='PlanEditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', models.JSONField()),
                ('suggested_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='accounts.sharedfoodplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
