# Generated by Django 5.2.7 on 2025-12-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_sharedfoodplan_planeditsuggestion'),
        ('accounts', '0016_userpreference'),
    ]

    operations = [
    ]
