# Generated by Django 5.2.7 on 2025-12-08 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakPopupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup_type', models.CharField(default='frozen', max_length=20)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('streak_value', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_popups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
    ]
