# Generated by Django 5.2.7 on 2025-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeditsuggestion',
            name='pending_changes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
