# Generated by Django 5.2.7 on 2025-12-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_planeditsuggestion_pending_changes'),
        ('accounts', '0019_streakpopuplog'),
    ]

    operations = [
    ]
