# Generated by Django 5.2.7 on 2025-12-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20251209_1345'),
        ('accounts', '0020_merge_20251209_1347'),
        ('accounts', '0020_merge_20251209_1402'),
    ]

    operations = [
    ]
