# Generated by Django 5.2.7 on 2025-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20251209_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sharedfoodplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
