# Generated by Django 5.2.7 on 2025-12-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_foodplan_updated_at_sharedfoodplan_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeditsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
