# Generated by Django 5.2.7 on 2025-12-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_planeditsuggestion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeditsuggestion',
            name='approved_changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='planeditsuggestion',
            name='rejected_changes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
