# Generated by Django 5.2.7 on 2025-12-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_planeditsuggestion_approved_changes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planeditsuggestion',
            name='approved_changes',
        ),
        migrations.RemoveField(
            model_name='planeditsuggestion',
            name='rejected_changes',
        ),
    ]
