# Generated by Django 5.2.7 on 2025-12-14 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_planeditsuggestion_approved_changes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_history',
                'indexes': [models.Index(fields=['user', 'place_id'], name='review_hist_user_id_0415ba_idx'), models.Index(fields=['user', 'review_date'], name='review_hist_user_id_ebced1_idx')],
            },
        ),
    ]
