# Generated by Django 5.2.7 on 2025-12-18 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_notificationdelaymetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequestDelayMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('send', 'Send Friend Request'), ('cancel', 'Cancel Request'), ('accept', 'Accept Request'), ('reject', 'Reject Request'), ('unfriend', 'Unfriend')], max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField()),
                ('delay_ms', models.IntegerField()),
                ('test_session', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_targets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'test_session'], name='accounts_fr_user_id_aec214_idx'), models.Index(fields=['created_at'], name='accounts_fr_created_8eb431_idx')],
            },
        ),
    ]
